name: Build EnxyAbilities

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v2

    - uses: lukka/get-cmake@latest

    - uses: lukka/run-vcpkg@v11

    # CACHE
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          build
          vcpkg_installed
          C:/vcpkg/packages
          C:/vcpkg/downloads
          C:/vcpkg/buildtrees
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Clean
      shell: cmd
      run: |
        if exist build rmdir /s /q build

    - name: Configure
      shell: cmd
      run: |
        cmake -B build ^
        -S . ^
        -A x64 ^
        -DCMAKE_BUILD_TYPE=Release ^
        -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
        -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ^
        -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake

    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: EnxyAbilities
        path: build/**/*.dll
